# Generated by Django 4.2 on 2026-05-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='prix',
            field=models.FloatField(default=0.0),
        ),
    ]
